[package]
name = "rish-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
rish-applets.workspace = true
rish-content.workspace = true
rish-core.workspace = true
rish-oci.workspace = true
rish-guest-protocol.workspace = true
rish-pull.workspace = true
rish-registry.workspace = true
rish-runtime.workspace = true
rish-softvm-x86_64.workspace = true
rish-vm.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile = "3.20"
