[package]
name = "rish-softvm-x86_64"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "0.22"
rish-core.workspace = true
rish-guest-protocol.workspace = true
rish-softvm-core.workspace = true
rish-vm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
rish-guest-agent.workspace = true
tempfile = "3.8"
