[package]
name = "rish-softvm-x86_64"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rish-core.workspace = true
rish-guest-protocol.workspace = true
rish-vm.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.8"
