//! Linux SETUP_RNG_SEED boot record. Entropy is supplied by the trusted host,
//! not generated by the deterministic CPU interpreter.

use super::bzimage::ZERO_PAGE_BASE;
use crate::{Cpu, CpuError};

pub const SEED_BYTES: usize = 64;
pub const RNG_SETUP_BASE: u64 = 0x30000;
const SETUP_DATA_POINTER: u64 = ZERO_PAGE_BASE + 0x250;

pub fn install(cpu: &mut Cpu, seed: &[u8; SEED_BYTES]) -> Result<(), CpuError> {
    let previous = cpu.memory.read_u64(SETUP_DATA_POINTER)?;
    if (RNG_SETUP_BASE..RNG_SETUP_BASE + 16 + SEED_BYTES as u64).contains(&previous) {
        return Err(CpuError::InvalidConfig(
            "RNG setup data is already installed".into(),
        ));
    }
    let mut header = [0; 16];
    header[..8].copy_from_slice(&previous.to_le_bytes());
    header[8..12].copy_from_slice(&9_u32.to_le_bytes());
    header[12..].copy_from_slice(&(SEED_BYTES as u32).to_le_bytes());
    cpu.memory.write(RNG_SETUP_BASE, &header)?;
    cpu.memory.write(RNG_SETUP_BASE + 16, seed)?;
    // Publish the pointer last. Linux mixes the payload into its RNG and
    // explicitly zeroes it while parsing SETUP_RNG_SEED.
    cpu.memory.write_u64(SETUP_DATA_POINTER, RNG_SETUP_BASE)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_record_uses_the_linux_header_and_preserves_an_existing_chain() {
        let mut cpu = Cpu::new(1, 0).unwrap();
        cpu.memory.write_u64(SETUP_DATA_POINTER, 0x31000).unwrap();
        let seed = [0x5a; SEED_BYTES]; // layout fixture, never production entropy
        install(&mut cpu, &seed).unwrap();
        assert_eq!(
            cpu.memory.read_u64(SETUP_DATA_POINTER).unwrap(),
            RNG_SETUP_BASE
        );
        assert_eq!(cpu.memory.read_u64(RNG_SETUP_BASE).unwrap(), 0x31000);
        assert_eq!(cpu.memory.read_u32(RNG_SETUP_BASE + 8).unwrap(), 9);
        assert_eq!(
            cpu.memory.read_u32(RNG_SETUP_BASE + 12).unwrap(),
            SEED_BYTES as u32
        );
        let mut actual = [0; SEED_BYTES];
        cpu.memory.read(RNG_SETUP_BASE + 16, &mut actual).unwrap();
        assert_eq!(actual, seed);
    }

    #[test]
    fn repeated_install_cannot_create_a_setup_data_cycle() {
        let mut cpu = Cpu::new(1, 0).unwrap();
        install(&mut cpu, &[0x5a; SEED_BYTES]).unwrap();
        assert!(install(&mut cpu, &[0x6a; SEED_BYTES]).is_err());
    }
}
